### ISSUE TITLE
Tests do not pass as cloned or on solution branch

### ISSUE THREAD

**Issue by bhollan** [learn-co-curriculum/quote-maker-react-lab#2]
When I clone and run `learn` on `master` or `solution` branch:
```
/home/brianh/code/labs/cooking-with-redux-v-000/src/store.js:18
  return (0, _redux.createStore)(_index2['default'], window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__());
                                                     ^

ReferenceError: window is not defined
    at configureStore (/home/brianh/code/labs/cooking-with-redux-v-000/src/store.js:5:35)
    at Object.<anonymous> (/home/brianh/code/labs/cooking-with-redux-v-000/src/store.js:8:22)
    at Module._compile (module.js:570:32)
    at loader (/home/brianh/code/labs/cooking-with-redux-v-000/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/brianh/code/labs/cooking-with-redux-v-000/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/brianh/code/labs/cooking-with-redux-v-000/test/addIngredients-test.js:5:1)
    at Module._compile (module.js:570:32)
    at loader (/home/brianh/code/labs/cooking-with-redux-v-000/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/brianh/code/labs/cooking-with-redux-v-000/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /home/brianh/code/labs/cooking-with-redux-v-000/node_modules/mocha/lib/mocha.js:230:27
    at Array.forEach (native)
    at Mocha.loadFiles (/home/brianh/code/labs/cooking-with-redux-v-000/node_modules/mocha/lib/mocha.js:227:14)
    at Mocha.run (/home/brianh/code/labs/cooking-with-redux-v-000/node_modules/mocha/lib/mocha.js:495:10)
    at Object.<anonymous> (/home/brianh/code/labs/cooking-with-redux-v-000/node_modules/mocha/bin/_mocha:469:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
/home/brianh/.rvm/gems/ruby-2.3.1/gems/learn-test-2.4.0/lib/learn_test/strategies/mocha.rb:49:in `results': undefined method `[]' for nil:NilClass (NoMethodError)
	from /home/brianh/.rvm/gems/ruby-2.3.1/gems/learn-test-2.4.0/lib/learn_test/runner.rb:68:in `push_results'
	from /home/brianh/.rvm/gems/ruby-2.3.1/gems/learn-test-2.4.0/lib/learn_test/runner.rb:19:in `run'
	from /home/brianh/.rvm/gems/ruby-2.3.1/gems/learn-test-2.4.0/bin/learn-test:60:in `<top (required)>'
	from /home/brianh/.rvm/gems/ruby-2.3.1/bin/learn-test:23:in `load'
	from /home/brianh/.rvm/gems/ruby-2.3.1/bin/learn-test:23:in `<main>'
	from /home/brianh/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /home/brianh/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by aturkewi** [comment]
Note: Running `npm test` does run the tests, but after all 27 finish,  it just hangs and you need to kill the process to get the terminal back.

**Comment by aturkewi** [comment]
Update: `npm test` is hanging because it has the `-w` flag (watch). This should _probably_ be removed? But it _does not_ fix the overall error.

**Comment by aturkewi** [comment]
@Lukeghenco any thoughts on this?

**Comment by aturkewi** [comment]
@JeffKatzy I'll tag you in here as well as it looks like you wrote this one. Any thoughts on what it might be?

**Comment by kwebster2** [comment]
@aturkewi @Lukeghenco 
The issue was because the test script was not using`mocha-multi` / outputting the results to`.results.json`, so the `learn-test` mocha strategy was using the default `  "node_modules/.bin/mocha -R mocha-multi --reporter-options spec=-,json=.results.json"` command, rather than using the test script defined in `package.json` (which includes the `test/helpers/browser.js` file). 

PR #4 fixes this

**Comment by mhornbacher** [comment]
Please merge this into the curriculum. it can be really confusing to see `window is not defined`

**Comment by kwebster2** [comment]
@Lukeghenco 
Had several students over the past week still experiencing this issue. The pending PR fixes it

**Comment by Lukeghenco** [comment]
@kwebster2 this lab has been rewritten and resolves these issues.
